### ISSUE TITLE
Please add Backgrid.getCountSelectedModels()

### ISSUE THREAD

**Issue by jeffreycahyono** [wyuenho/backgrid-select-all#11]
It would be useful for this extension to have  ```Backgrid.getCountSelectedModels()``` to retieve the number of selected models,

The use case is like the Gmail UI button, where certain toolbar button is displayed only when there are some row selected. The toolbar listens to ```backgrid:select``` event and retrieve  ```Backgrid.getCountSelectedModels()```. If the result is bigger than zero the groups of toolbar shown

**Comment by wyuenho** [comment]
There isn't a way to know for sure whether a model had been selected without checking to see if it's in a collection, so just return the length of `selectedModels` won't work.
