### ISSUE TITLE
Pressing up or down arrow after clicking select-all header cell causes error

### ISSUE THREAD

**Issue by libbyrobinson** [wyuenho/backgrid-select-all#12]
Happening in most up to date version of extension (v 0.3.5)

If you click on the select-all checkbox in the grids header cell, and then press either the up or down arrow, you get a js error. 

Comes from line 106 of backgrid-select-all.js, in the onKeydown method, because this.model is null.
```this.model.trigger("backgrid:edited", this.model, this.column, command);```

Included jsfiddle to repro: http://jsfiddle.net/ED7yW/

**Comment by wyuenho** [comment]
That fiddle works fine to me.
